app:
  domain: localhost
  port: 3030

rendrApp:
  howdy: "ohai!"

assets:
  minify: false
  cdn:
    protocol: http
    cnames: ['localhost']
    pathPrefix: ''

api:
  default: 
    host: localhost:3030
    protocol: http
  ts-api:
    host: localhost:5000
    protocol: http