App:
  domain: localhost
  port: 3030

assets:
  minify: false
  cdn:
    protocol: http
    cnames: ['localhost']
    pathPrefix: ''

api:
  default: 
    host: localhost:3030
    protocol: http
  ts-api:
    host: sheltered-hamlet-5481.herokuapp.com
    protocol: http